<a href="https://colab.research.google.com/github/Abeer-24/NLP/blob/main/Information_Extraction_(IE)_from_structured_unstructured_documents.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install -q spacy pandas
!python -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 79.6 MB/s  0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [2]:
import pandas as pd
import spacy
import re

nlp = spacy.load("en_core_web_sm")

In [3]:
data = {
    "Name": ["Rahul Sharma", "Priya Verma", "Amit Kumar"],
    "Email": [
        "rahul@gmail.com",
        "priya@gmail.com",
        "amit@gmail.com"
    ],
    "City": ["Delhi", "Mumbai", "Noida"],
    "Course": ["CSE", "AI", "IT"]
}

df = pd.DataFrame(data)

print("Structured Document:")
display(df)

Structured Document:

           Name            Email    City Course
0  Rahul Sharma  rahul@gmail.com   Delhi    CSE
1   Priya Verma  priya@gmail.com  Mumbai     AI
2    Amit Kumar   amit@gmail.com   Noida     IT

In [4]:
print("Names:")
print(df["Name"].tolist())

print("\nEmail Addresses:")
print(df["Email"].tolist())

print("\nCities:")
print(df["City"].tolist())

print("\nCourses:")
print(df["Course"].tolist())

Names:
['Rahul Sharma', 'Priya Verma', 'Amit Kumar']

Email Addresses:
['rahul@gmail.com', 'priya@gmail.com', 'amit@gmail.com']

Cities:
['Delhi', 'Mumbai', 'Noida']

Courses:
['CSE', 'AI', 'IT']

In [5]:
text = """
Rahul Sharma works at Google in Delhi.
He joined the company on 15 January 2024.
His email is rahul@gmail.com and phone number is 9876543210.

Priya Verma works at Microsoft in Mumbai.
She joined on 20 March 2023.
Her email is priya@gmail.com.
"""
print(text)

Rahul Sharma works at Google in Delhi.
He joined the company on 15 January 2024.
His email is rahul@gmail.com and phone number is 9876543210.

Priya Verma works at Microsoft in Mumbai.
She joined on 20 March 2023.
Her email is priya@gmail.com.

In [6]:
doc = nlp(text)

for ent in doc.ents:
    print(ent.text, ":", ent.label_)

Rahul Sharma : PERSON
Google : ORG
Delhi : GPE
15 January 2024 : DATE
9876543210 : DATE
Priya Verma : PERSON
Microsoft : ORG
Mumbai : GPE
20 March 2023 : DATE

In [7]:
emails = re.findall(
    r'[\w.-]+@[\w.-]+\.\w+',
    text
)

print("Extracted Emails:")
print(emails)

Extracted Emails:
['rahul@gmail.com', 'priya@gmail.com']

In [8]:
phone_numbers = re.findall(
    r'\b\d{10}\b',
    text
)

print("Extracted Phone Numbers:")
print(phone_numbers)

Extracted Phone Numbers:
['9876543210']

In [9]:
extracted_data = {
    "Emails": emails,
    "Phone Numbers": phone_numbers
}

print("Extracted Information:")
display(pd.DataFrame({
    "Emails": pd.Series(emails),
    "Phone Numbers": pd.Series(phone_numbers)
}))

Extracted Information:

            Emails Phone Numbers
0  rahul@gmail.com    9876543210
1  priya@gmail.com           NaN

In [10]:
print("Noun Phrases:")

for chunk in doc.noun_chunks:
    print(chunk.text)

print("\nImportant Keywords:")

for token in doc:
    if token.pos_ in ["NOUN", "PROPN"] and not token.is_stop:
        print(token.text)

Noun Phrases:

Rahul Sharma
Google
Delhi
He
the company
15 January
His email
phone number
Priya Verma
Microsoft
Mumbai
She
20 March
Her email

Important Keywords:
Rahul
Sharma
Google
Delhi
company
January
email
phone
number
Priya
Verma
Microsoft
Mumbai
March
email

In [11]:
print("INFORMATION EXTRACTION SUMMARY")
print("--------------------------------")

print("Names and Organizations:")
for ent in doc.ents:
    if ent.label_ in ["PERSON", "ORG"]:
        print(ent.text, "-", ent.label_)

print("\nEmails:", emails)
print("Phone Numbers:", phone_numbers)

INFORMATION EXTRACTION SUMMARY
--------------------------------
Names and Organizations:
Rahul Sharma - PERSON
Google - ORG
Priya Verma - PERSON
Microsoft - ORG

Emails: ['rahul@gmail.com', 'priya@gmail.com']
Phone Numbers: ['9876543210']